version: "3.1"
services:

  app:
    build: .
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./src:/code/src
    command: ["--reload"]
    depends_on:
      - mongo
    env_file:
      - .env

  mongo:
    image: mongo:6.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_ROOT}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_ROOT_PASSWORD}"
    volumes:
      - mongo_data:/data/db
    env_file:
      - .env

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://${MONGO_ROOT}:${MONGO_ROOT_PASSWORD}@mongo:27017/"
    depends_on:
      - mongo
    env_file:
      - .env

volumes:
  mongo_data:
    driver: local
